@Account.API_HostAddress = http://localhost:5063

### Get all users
GET {{Account.API_HostAddress}}/api/users
Accept: application/json

###

### Get user by ID
GET {{Account.API_HostAddress}}/api/users/1
Accept: application/json

###

### Update user with first name and last name changes
PUT {{Account.API_HostAddress}}/api/users/1
Content-Type: application/json

{
  "email": "updated.email@example.com",
  "isEmailVerified": true,
  "firstName": "UpdatedFirst",
  "lastName": "UpdatedLast"
}

###

### Update user with only first name change
PUT {{Account.API_HostAddress}}/api/users/1
Content-Type: application/json

{
  "email": "updated.email@example.com",
  "isEmailVerified": true,
  "firstName": "NewFirst"
}

###

### Update user with only last name change
PUT {{Account.API_HostAddress}}/api/users/1
Content-Type: application/json

{
  "email": "updated.email@example.com",
  "isEmailVerified": true,
  "lastName": "NewLast"
}

###
