version: '3.8'

services:
  account-api:
    build:
      context: .
      dockerfile: Account.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - microservices-network

  audit-api:
    build:
      context: .
      dockerfile: Audit.API/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - microservices-network

  businesslogic-api:
    build:
      context: .
      dockerfile: BusinessLogic.API/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
